//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RS.rc
//
#define IDB_BG                          102
#define IDB_FUDA1                       103
#define IDB_FUDA2                       104
#define IDB_FUDA3                       105
#define IDB_FUDA4                       106
#define IDB_FUDA5                       107
#define IDB_FUDA6                       108
#define IDB_FUDA7                       109
#define IDB_FUDA8                       110
#define IDB_FUDA9                       111
#define IDB_FUDA10                      112
#define IDB_FUDA11                      113
#define IDB_FUDA12                      114
#define IDB_FUDA13                      115
#define IDB_FUDA14                      116
#define IDB_FUDA15                      117
#define IDB_FUDA16                      118
#define IDB_FUDA17                      119
#define IDB_FUDA18                      120
#define IDB_FUDA19                      121
#define IDB_FUDA20                      122
#define IDB_FUDA21                      123
#define IDB_FUDA22                      124
#define IDB_FUDA23                      125
#define IDB_FUDA24                      126
#define IDB_FUDA25                      127
#define IDB_FUDA26                      128
#define IDB_FUDA27                      129
#define IDB_FUDA28                      130
#define IDB_FUDA29                      131
#define IDB_FUDA30                      132
#define IDB_FUDA31                      133
#define IDB_FUDA32                      134
#define IDB_FUDA33                      135
#define IDB_FUDA34                      136
#define IDB_FUDA35                      137
#define IDB_FUDA36                      138
#define IDB_FUDA37                      139
#define IDB_FUDA38                      140
#define IDB_FUDA39                      141
#define IDB_FUDA40                      142
#define IDB_FUDA41                      143
#define IDB_FUDA42                      144
#define IDB_FUDA43                      145
#define IDB_FUDA44                      146
#define IDB_FUDA45                      147
#define IDB_FUDA46                      148
#define IDB_FUDA47                      149
#define IDB_FUDA48                      150
#define IDB_URA                         151
#define IDB_STR_1G                      152
#define IDB_STR_2G                      153
#define IDB_STR_3G                      154
#define IDB_STR_4G                      155
#define IDB_STR_5G                      156
#define IDB_STR_6G                      157
#define IDB_STR_7G                      158
#define IDB_STR_8G                      159
#define IDB_STR_9G                      160
#define IDB_STR_10G                     161
#define IDB_STR_11G                     162
#define IDB_STR_12G                     163
#define IDB_STR_ANO                     164
#define IDB_STR_ERA                     165
#define IDB_STR_WAO                     166
#define IDB_STR_COM                     167
#define IDB_STR_YOU                     168
#define IDB_YAKU                        169
#define IDB_STR_GOKO                    170
#define IDB_STR_SHIKO                   171
#define IDB_STR_AMESHIKO                172
#define IDB_STR_SANKO                   173
#define IDB_STR_HANAMI                  174
#define IDB_STR_TSUKIMI                 175
#define IDB_STR_AKATAN                  176
#define IDB_STR_AOTAN                   177
#define IDB_STR_INOSHIKA                178
#define IDB_STR_TANE                    179
#define IDB_STR_TAN                     180
#define IDB_STR_KASU                    181
#define IDB_STR_OYAKEN                  182
#define IDB_STR_KOIKOI1                 183
#define IDB_STR_KOIKOI2                 184
#define IDB_STR_HAI                     185
#define IDB_STR_IIE                     186
#define IDB_STR_B_0                     187
#define IDB_STR_B_1                     188
#define IDB_STR_B_2                     189
#define IDB_STR_B_3                     190
#define IDB_STR_B_4                     191
#define IDB_STR_B_5                     192
#define IDB_STR_B_6                     193
#define IDB_STR_B_7                     194
#define IDB_STR_B_8                     195
#define IDB_STR_B_9                     196
#define IDB_STR_B_MON                   197
#define IDB_STR_B_GOUKEI                198
#define IDB_STR_W_0                     199
#define IDB_STR_W_1                     200
#define IDB_STR_W_2                     201
#define IDB_STR_W_3                     202
#define IDB_STR_W_4                     203
#define IDB_STR_W_5                     204
#define IDB_STR_W_6                     205
#define IDB_STR_W_7                     206
#define IDB_STR_W_8                     207
#define IDB_STR_W_9                     208
#define IDB_STR_W_MON                   209
#define IDB_STR_W_GOUKEI                210
#define IDB_STR_WAK                     211
#define IDB_STR_ANK                     212
#define IDB_STR_DRAW                    213
#define IDR_MP3_ACHEIVE                 238
#define IDR_MP3_WIN                     239
#define IDR_MP3_ENDING                  240
#define IDR_WAV_PUT1                    244
#define IDR_WAV_PUT2                    245

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        246
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
